//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Ecm.WebReferences.SystemService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SystemServiceSoap", Namespace="http://tempuri.org/")]
    public partial class SystemService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UploadFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetConfigFilesOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPathOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_Rex_Dm_Heso_Chuongtrinh_Collection3OperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_Rex_Dm_Heso_Chuongtrinh_By_NhomhesoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Insert_Rex_Dm_Heso_ChuongtrinhOperationCompleted;
        
        private System.Threading.SendOrPostCallback Update_Rex_Dm_Heso_ChuongtrinhOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_Rex_Dm_Heso_ChuongtrinhOperationCompleted;
        
        private System.Threading.SendOrPostCallback Update_Rex_Dm_Heso_Chuongtrinh_CollectionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SystemService() {
            this.Url = global::Ecm.WebReferences.Properties.Settings.Default.Ecm_WebReferences_SystemService_SystemService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UploadFileCompletedEventHandler UploadFileCompleted;
        
        /// <remarks/>
        public event GetConfigFilesCompletedEventHandler GetConfigFilesCompleted;
        
        /// <remarks/>
        public event DownloadFileCompletedEventHandler DownloadFileCompleted;
        
        /// <remarks/>
        public event GetPathCompletedEventHandler GetPathCompleted;
        
        /// <remarks/>
        public event Get_Rex_Dm_Heso_Chuongtrinh_Collection3CompletedEventHandler Get_Rex_Dm_Heso_Chuongtrinh_Collection3Completed;
        
        /// <remarks/>
        public event Get_Rex_Dm_Heso_Chuongtrinh_By_NhomhesoCompletedEventHandler Get_Rex_Dm_Heso_Chuongtrinh_By_NhomhesoCompleted;
        
        /// <remarks/>
        public event Insert_Rex_Dm_Heso_ChuongtrinhCompletedEventHandler Insert_Rex_Dm_Heso_ChuongtrinhCompleted;
        
        /// <remarks/>
        public event Update_Rex_Dm_Heso_ChuongtrinhCompletedEventHandler Update_Rex_Dm_Heso_ChuongtrinhCompleted;
        
        /// <remarks/>
        public event Delete_Rex_Dm_Heso_ChuongtrinhCompletedEventHandler Delete_Rex_Dm_Heso_ChuongtrinhCompleted;
        
        /// <remarks/>
        public event Update_Rex_Dm_Heso_Chuongtrinh_CollectionCompletedEventHandler Update_Rex_Dm_Heso_Chuongtrinh_CollectionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UploadFile([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] f, string fileName, string profile) {
            object[] results = this.Invoke("UploadFile", new object[] {
                        f,
                        fileName,
                        profile});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UploadFileAsync(byte[] f, string fileName, string profile) {
            this.UploadFileAsync(f, fileName, profile, null);
        }
        
        /// <remarks/>
        public void UploadFileAsync(byte[] f, string fileName, string profile, object userState) {
            if ((this.UploadFileOperationCompleted == null)) {
                this.UploadFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadFileOperationCompleted);
            }
            this.InvokeAsync("UploadFile", new object[] {
                        f,
                        fileName,
                        profile}, this.UploadFileOperationCompleted, userState);
        }
        
        private void OnUploadFileOperationCompleted(object arg) {
            if ((this.UploadFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadFileCompleted(this, new UploadFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetConfigFiles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetConfigFiles(string profile) {
            object[] results = this.Invoke("GetConfigFiles", new object[] {
                        profile});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetConfigFilesAsync(string profile) {
            this.GetConfigFilesAsync(profile, null);
        }
        
        /// <remarks/>
        public void GetConfigFilesAsync(string profile, object userState) {
            if ((this.GetConfigFilesOperationCompleted == null)) {
                this.GetConfigFilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetConfigFilesOperationCompleted);
            }
            this.InvokeAsync("GetConfigFiles", new object[] {
                        profile}, this.GetConfigFilesOperationCompleted, userState);
        }
        
        private void OnGetConfigFilesOperationCompleted(object arg) {
            if ((this.GetConfigFilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetConfigFilesCompleted(this, new GetConfigFilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DownloadFile(string FName, string profile) {
            object[] results = this.Invoke("DownloadFile", new object[] {
                        FName,
                        profile});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void DownloadFileAsync(string FName, string profile) {
            this.DownloadFileAsync(FName, profile, null);
        }
        
        /// <remarks/>
        public void DownloadFileAsync(string FName, string profile, object userState) {
            if ((this.DownloadFileOperationCompleted == null)) {
                this.DownloadFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadFileOperationCompleted);
            }
            this.InvokeAsync("DownloadFile", new object[] {
                        FName,
                        profile}, this.DownloadFileOperationCompleted, userState);
        }
        
        private void OnDownloadFileOperationCompleted(object arg) {
            if ((this.DownloadFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadFileCompleted(this, new DownloadFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPath", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPath() {
            object[] results = this.Invoke("GetPath", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPathAsync() {
            this.GetPathAsync(null);
        }
        
        /// <remarks/>
        public void GetPathAsync(object userState) {
            if ((this.GetPathOperationCompleted == null)) {
                this.GetPathOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPathOperationCompleted);
            }
            this.InvokeAsync("GetPath", new object[0], this.GetPathOperationCompleted, userState);
        }
        
        private void OnGetPathOperationCompleted(object arg) {
            if ((this.GetPathCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPathCompleted(this, new GetPathCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Rex_Dm_Heso_Chuongtrinh_Collection3", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_Rex_Dm_Heso_Chuongtrinh_Collection3() {
            object[] results = this.Invoke("Get_Rex_Dm_Heso_Chuongtrinh_Collection3", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_Rex_Dm_Heso_Chuongtrinh_Collection3Async() {
            this.Get_Rex_Dm_Heso_Chuongtrinh_Collection3Async(null);
        }
        
        /// <remarks/>
        public void Get_Rex_Dm_Heso_Chuongtrinh_Collection3Async(object userState) {
            if ((this.Get_Rex_Dm_Heso_Chuongtrinh_Collection3OperationCompleted == null)) {
                this.Get_Rex_Dm_Heso_Chuongtrinh_Collection3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Rex_Dm_Heso_Chuongtrinh_Collection3OperationCompleted);
            }
            this.InvokeAsync("Get_Rex_Dm_Heso_Chuongtrinh_Collection3", new object[0], this.Get_Rex_Dm_Heso_Chuongtrinh_Collection3OperationCompleted, userState);
        }
        
        private void OnGet_Rex_Dm_Heso_Chuongtrinh_Collection3OperationCompleted(object arg) {
            if ((this.Get_Rex_Dm_Heso_Chuongtrinh_Collection3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Rex_Dm_Heso_Chuongtrinh_Collection3Completed(this, new Get_Rex_Dm_Heso_Chuongtrinh_Collection3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Rex_Dm_Heso_Chuongtrinh_By_Nhomheso", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_Rex_Dm_Heso_Chuongtrinh_By_Nhomheso(object nhom) {
            object[] results = this.Invoke("Get_Rex_Dm_Heso_Chuongtrinh_By_Nhomheso", new object[] {
                        nhom});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_Rex_Dm_Heso_Chuongtrinh_By_NhomhesoAsync(object nhom) {
            this.Get_Rex_Dm_Heso_Chuongtrinh_By_NhomhesoAsync(nhom, null);
        }
        
        /// <remarks/>
        public void Get_Rex_Dm_Heso_Chuongtrinh_By_NhomhesoAsync(object nhom, object userState) {
            if ((this.Get_Rex_Dm_Heso_Chuongtrinh_By_NhomhesoOperationCompleted == null)) {
                this.Get_Rex_Dm_Heso_Chuongtrinh_By_NhomhesoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Rex_Dm_Heso_Chuongtrinh_By_NhomhesoOperationCompleted);
            }
            this.InvokeAsync("Get_Rex_Dm_Heso_Chuongtrinh_By_Nhomheso", new object[] {
                        nhom}, this.Get_Rex_Dm_Heso_Chuongtrinh_By_NhomhesoOperationCompleted, userState);
        }
        
        private void OnGet_Rex_Dm_Heso_Chuongtrinh_By_NhomhesoOperationCompleted(object arg) {
            if ((this.Get_Rex_Dm_Heso_Chuongtrinh_By_NhomhesoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Rex_Dm_Heso_Chuongtrinh_By_NhomhesoCompleted(this, new Get_Rex_Dm_Heso_Chuongtrinh_By_NhomhesoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insert_Rex_Dm_Heso_Chuongtrinh", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object Insert_Rex_Dm_Heso_Chuongtrinh(Rex_Dm_Heso_Chuongtrinh Rex_Dm_Heso_Chuongtrinh) {
            object[] results = this.Invoke("Insert_Rex_Dm_Heso_Chuongtrinh", new object[] {
                        Rex_Dm_Heso_Chuongtrinh});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void Insert_Rex_Dm_Heso_ChuongtrinhAsync(Rex_Dm_Heso_Chuongtrinh Rex_Dm_Heso_Chuongtrinh) {
            this.Insert_Rex_Dm_Heso_ChuongtrinhAsync(Rex_Dm_Heso_Chuongtrinh, null);
        }
        
        /// <remarks/>
        public void Insert_Rex_Dm_Heso_ChuongtrinhAsync(Rex_Dm_Heso_Chuongtrinh Rex_Dm_Heso_Chuongtrinh, object userState) {
            if ((this.Insert_Rex_Dm_Heso_ChuongtrinhOperationCompleted == null)) {
                this.Insert_Rex_Dm_Heso_ChuongtrinhOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsert_Rex_Dm_Heso_ChuongtrinhOperationCompleted);
            }
            this.InvokeAsync("Insert_Rex_Dm_Heso_Chuongtrinh", new object[] {
                        Rex_Dm_Heso_Chuongtrinh}, this.Insert_Rex_Dm_Heso_ChuongtrinhOperationCompleted, userState);
        }
        
        private void OnInsert_Rex_Dm_Heso_ChuongtrinhOperationCompleted(object arg) {
            if ((this.Insert_Rex_Dm_Heso_ChuongtrinhCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Insert_Rex_Dm_Heso_ChuongtrinhCompleted(this, new Insert_Rex_Dm_Heso_ChuongtrinhCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update_Rex_Dm_Heso_Chuongtrinh", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object Update_Rex_Dm_Heso_Chuongtrinh(Rex_Dm_Heso_Chuongtrinh Rex_Dm_Heso_Chuongtrinh) {
            object[] results = this.Invoke("Update_Rex_Dm_Heso_Chuongtrinh", new object[] {
                        Rex_Dm_Heso_Chuongtrinh});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void Update_Rex_Dm_Heso_ChuongtrinhAsync(Rex_Dm_Heso_Chuongtrinh Rex_Dm_Heso_Chuongtrinh) {
            this.Update_Rex_Dm_Heso_ChuongtrinhAsync(Rex_Dm_Heso_Chuongtrinh, null);
        }
        
        /// <remarks/>
        public void Update_Rex_Dm_Heso_ChuongtrinhAsync(Rex_Dm_Heso_Chuongtrinh Rex_Dm_Heso_Chuongtrinh, object userState) {
            if ((this.Update_Rex_Dm_Heso_ChuongtrinhOperationCompleted == null)) {
                this.Update_Rex_Dm_Heso_ChuongtrinhOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate_Rex_Dm_Heso_ChuongtrinhOperationCompleted);
            }
            this.InvokeAsync("Update_Rex_Dm_Heso_Chuongtrinh", new object[] {
                        Rex_Dm_Heso_Chuongtrinh}, this.Update_Rex_Dm_Heso_ChuongtrinhOperationCompleted, userState);
        }
        
        private void OnUpdate_Rex_Dm_Heso_ChuongtrinhOperationCompleted(object arg) {
            if ((this.Update_Rex_Dm_Heso_ChuongtrinhCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Update_Rex_Dm_Heso_ChuongtrinhCompleted(this, new Update_Rex_Dm_Heso_ChuongtrinhCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Delete_Rex_Dm_Heso_Chuongtrinh", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object Delete_Rex_Dm_Heso_Chuongtrinh(Rex_Dm_Heso_Chuongtrinh Rex_Dm_Heso_Chuongtrinh) {
            object[] results = this.Invoke("Delete_Rex_Dm_Heso_Chuongtrinh", new object[] {
                        Rex_Dm_Heso_Chuongtrinh});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_Rex_Dm_Heso_ChuongtrinhAsync(Rex_Dm_Heso_Chuongtrinh Rex_Dm_Heso_Chuongtrinh) {
            this.Delete_Rex_Dm_Heso_ChuongtrinhAsync(Rex_Dm_Heso_Chuongtrinh, null);
        }
        
        /// <remarks/>
        public void Delete_Rex_Dm_Heso_ChuongtrinhAsync(Rex_Dm_Heso_Chuongtrinh Rex_Dm_Heso_Chuongtrinh, object userState) {
            if ((this.Delete_Rex_Dm_Heso_ChuongtrinhOperationCompleted == null)) {
                this.Delete_Rex_Dm_Heso_ChuongtrinhOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_Rex_Dm_Heso_ChuongtrinhOperationCompleted);
            }
            this.InvokeAsync("Delete_Rex_Dm_Heso_Chuongtrinh", new object[] {
                        Rex_Dm_Heso_Chuongtrinh}, this.Delete_Rex_Dm_Heso_ChuongtrinhOperationCompleted, userState);
        }
        
        private void OnDelete_Rex_Dm_Heso_ChuongtrinhOperationCompleted(object arg) {
            if ((this.Delete_Rex_Dm_Heso_ChuongtrinhCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_Rex_Dm_Heso_ChuongtrinhCompleted(this, new Delete_Rex_Dm_Heso_ChuongtrinhCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update_Rex_Dm_Heso_Chuongtrinh_Collection", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object Update_Rex_Dm_Heso_Chuongtrinh_Collection(System.Data.DataSet ds_Rex_Dm_Heso_Chuongtrinh) {
            object[] results = this.Invoke("Update_Rex_Dm_Heso_Chuongtrinh_Collection", new object[] {
                        ds_Rex_Dm_Heso_Chuongtrinh});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void Update_Rex_Dm_Heso_Chuongtrinh_CollectionAsync(System.Data.DataSet ds_Rex_Dm_Heso_Chuongtrinh) {
            this.Update_Rex_Dm_Heso_Chuongtrinh_CollectionAsync(ds_Rex_Dm_Heso_Chuongtrinh, null);
        }
        
        /// <remarks/>
        public void Update_Rex_Dm_Heso_Chuongtrinh_CollectionAsync(System.Data.DataSet ds_Rex_Dm_Heso_Chuongtrinh, object userState) {
            if ((this.Update_Rex_Dm_Heso_Chuongtrinh_CollectionOperationCompleted == null)) {
                this.Update_Rex_Dm_Heso_Chuongtrinh_CollectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate_Rex_Dm_Heso_Chuongtrinh_CollectionOperationCompleted);
            }
            this.InvokeAsync("Update_Rex_Dm_Heso_Chuongtrinh_Collection", new object[] {
                        ds_Rex_Dm_Heso_Chuongtrinh}, this.Update_Rex_Dm_Heso_Chuongtrinh_CollectionOperationCompleted, userState);
        }
        
        private void OnUpdate_Rex_Dm_Heso_Chuongtrinh_CollectionOperationCompleted(object arg) {
            if ((this.Update_Rex_Dm_Heso_Chuongtrinh_CollectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Update_Rex_Dm_Heso_Chuongtrinh_CollectionCompleted(this, new Update_Rex_Dm_Heso_Chuongtrinh_CollectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Rex_Dm_Heso_Chuongtrinh {
        
        private object id_Heso_ChuongtrinhField;
        
        private object ma_Heso_ChuongtrinhField;
        
        private object ten_Heso_ChuongtrinhField;
        
        private object hesoField;
        
        private object nhom_Heso_ChuongtrinhField;
        
        private object ghichuField;
        
        private object regxField;
        
        /// <remarks/>
        public object Id_Heso_Chuongtrinh {
            get {
                return this.id_Heso_ChuongtrinhField;
            }
            set {
                this.id_Heso_ChuongtrinhField = value;
            }
        }
        
        /// <remarks/>
        public object Ma_Heso_Chuongtrinh {
            get {
                return this.ma_Heso_ChuongtrinhField;
            }
            set {
                this.ma_Heso_ChuongtrinhField = value;
            }
        }
        
        /// <remarks/>
        public object Ten_Heso_Chuongtrinh {
            get {
                return this.ten_Heso_ChuongtrinhField;
            }
            set {
                this.ten_Heso_ChuongtrinhField = value;
            }
        }
        
        /// <remarks/>
        public object Heso {
            get {
                return this.hesoField;
            }
            set {
                this.hesoField = value;
            }
        }
        
        /// <remarks/>
        public object Nhom_Heso_Chuongtrinh {
            get {
                return this.nhom_Heso_ChuongtrinhField;
            }
            set {
                this.nhom_Heso_ChuongtrinhField = value;
            }
        }
        
        /// <remarks/>
        public object Ghichu {
            get {
                return this.ghichuField;
            }
            set {
                this.ghichuField = value;
            }
        }
        
        /// <remarks/>
        public object Regx {
            get {
                return this.regxField;
            }
            set {
                this.regxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UploadFileCompletedEventHandler(object sender, UploadFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetConfigFilesCompletedEventHandler(object sender, GetConfigFilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetConfigFilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetConfigFilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void DownloadFileCompletedEventHandler(object sender, DownloadFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetPathCompletedEventHandler(object sender, GetPathCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPathCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPathCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Get_Rex_Dm_Heso_Chuongtrinh_Collection3CompletedEventHandler(object sender, Get_Rex_Dm_Heso_Chuongtrinh_Collection3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Rex_Dm_Heso_Chuongtrinh_Collection3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Rex_Dm_Heso_Chuongtrinh_Collection3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Get_Rex_Dm_Heso_Chuongtrinh_By_NhomhesoCompletedEventHandler(object sender, Get_Rex_Dm_Heso_Chuongtrinh_By_NhomhesoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Rex_Dm_Heso_Chuongtrinh_By_NhomhesoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Rex_Dm_Heso_Chuongtrinh_By_NhomhesoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Insert_Rex_Dm_Heso_ChuongtrinhCompletedEventHandler(object sender, Insert_Rex_Dm_Heso_ChuongtrinhCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Insert_Rex_Dm_Heso_ChuongtrinhCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Insert_Rex_Dm_Heso_ChuongtrinhCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Update_Rex_Dm_Heso_ChuongtrinhCompletedEventHandler(object sender, Update_Rex_Dm_Heso_ChuongtrinhCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Update_Rex_Dm_Heso_ChuongtrinhCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Update_Rex_Dm_Heso_ChuongtrinhCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Delete_Rex_Dm_Heso_ChuongtrinhCompletedEventHandler(object sender, Delete_Rex_Dm_Heso_ChuongtrinhCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_Rex_Dm_Heso_ChuongtrinhCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_Rex_Dm_Heso_ChuongtrinhCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void Update_Rex_Dm_Heso_Chuongtrinh_CollectionCompletedEventHandler(object sender, Update_Rex_Dm_Heso_Chuongtrinh_CollectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Update_Rex_Dm_Heso_Chuongtrinh_CollectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Update_Rex_Dm_Heso_Chuongtrinh_CollectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591